### ISSUE TITLE
[Bug] 依赖更新问题

### ISSUE THREAD

**Issue by xlh001** [batu1579/hamibot-starter#13]
**错误描述**
npm install 安装后提示存在14个漏洞，使用npm audit fix 修复后无法正常编译

**错误复现**
git clone https://github.com/batu1579/hamibot-starter.git
npm install
npm audit fix

**行为预期**
可以正常运行

**截图**
![image](https://github.com/batu1579/hamibot-starter/assets/26201873/d473b25a-b95d-4119-b574-92afb0ebb263)

**机器人型号（请填写以下信息）：**

- 设备型号：[例如：红米 K40]
- 操作系统：[例如：MIUI 12]
- Hamibot 版本：[例如：1.2.0]

**其他说明**
任何有关该问题的其他说明。

**Comment by batu1579** [comment]
嗨~

很抱歉我这里没法复现你遇到的问题，可能需要你提供更多信息QAQ。下面是我运行的效果：

![image](https://github.com/batu1579/hamibot-starter/assets/51915056/0b457af6-82dc-41aa-8cc8-6f48a65738e6)

但是我看你截图中的路径，觉得也许是因为你没有将路径切换到项目目录下（在克隆项目以后需要使用 `cd` 命令切换到 `hamibot-starter` 文件夹下）,一般来说完整的指令应该是：

```bash
// 将仓库克隆到本地
git clone https://github.com/batu1579/hamibot-starter.git

// 将目录切换到仓库
cd ./hamibot-starter

// 使用 npm 安装依赖
npm install
```

当然以上只是我通过你截图中的信息进行的猜测，可能和实际情况不符。也有可能和 CNPM 、 npm 源 、 npm 缓存或者你的网络代理有关？

如果你能够提供更详细的信息，会方便我定位问题。

等你回复~!

**Comment by xlh001** [comment]
npm audit fix
修复后无法正常编译

**Comment by batu1579** [comment]
因为里面有以前版本的依赖，不要修复直接运行

```bash
npm run build
```

应该就可以了

**Comment by xlh001** [comment]
好的
