### ISSUE TITLE
[Bug]模板使用 触摸操作模块 click函数返回参数类型不匹配 

### ISSUE THREAD

**Issue by xlh001** [batu1579/hamibot-starter#14]
**错误描述**
touch-operation.d.ts 模块中 setScreenMetrics、click、longClick、press、swipe 函数均在说明中标注返回是否成功，其函数返回类型应该修改为boolean类型而不是使用void

**错误复现**
产生 Bug 的代码或要复现 Bug 需要进行的操作（这有助于尽快定位问题）。

**行为预期**
清晰而简明的描述一下你期望这段代码或进行的操作产生的结果。

**截图**
如果可以的话，添加截图来帮助解释您遇到的问题。

**机器人型号（请填写以下信息）：**

- 设备型号：[例如：红米 K40]
- 操作系统：[例如：MIUI 12]
- Hamibot 版本：[例如：1.2.0]

**其他说明**
任何有关该问题的其他说明。

**Comment by batu1579** [comment]
hi @xlh001 

目前这个仓库里的类型声明并没有在维护，我把它存放在了另外的地方： [hamibot-types](https://github.com/batu1579/hamibot-types)

你可以使用里面自带的脚本来方便的获取类型声明（推荐 hamibot 代理的那个）。另外如果你使用这个仓库为模板创建项目的话需要根据说明文档里的 [迁移说明](https://github.com/batu1579/hamibot-types#%EF%B8%8F-%E8%BF%81%E7%A7%BB%E8%AF%B4%E6%98%8E) 来进行一下简单的调整。

我刚才检查了一下你提到的这些函数，`click`、`longClick`、`press`、`swipe` 这几个函数的声明在 hamibot-types 里面的声明是没有问题的，`setScreenMetrics` 函数的返回值类型在文档当中就没有具体描述。我测试过以后认为这个函数确实没有返回值，测试代码如下：

```typescript
let status = setScreenMetrics(device.width, device.height)
console.log('status',status)
```

得到的结果截图如下：

![image](https://github.com/batu1579/hamibot-starter/assets/51915056/cfa99f85-3cf4-46ea-ad23-5b241c7a56d7)

可以看到返回的值是 `undefined` 所以我认为应该是没有返回值。

希望能够帮到你，等你回复~

**Comment by xlh001** [comment]
好的，我调整一下代码判断逻辑
