### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by spirit223** [batu1579/hamibot-starter#17]
fork这个仓库后直接打包还是会出现
The 'show console' field in the configuration is invaild
这个控制台检查是无法绕过的吗,我检查了我的config.json里面json数组第二个对象的"value"字段是true, 并且我的hamibot悬浮窗权限已经开始并可以正常使用hamibot悬浮球
如果不可绕过那我应该通过什么办法才能够正常运行脚本?

**Comment by batu1579** [comment]
这个 issue 和之前的 #15  重复了我们还是在原来的地方讨论叭~

我先把这个 issue 关上辣
