### ISSUE TITLE
[Bug]华为手机有些功能补兼容无法实现

### ISSUE THREAD

**Issue by wytskshu** [batu1579/hamibot-starter#19]
**错误描述**
华为mate40鸿蒙4.0
toast，还有launch 都无法使用没有反应

**错误复现**
产生 Bug 的代码或要复现 Bug 需要进行的操作（这有助于尽快定位问题）。

还有怎么调用原生java api功能怎么实现

**Comment by batu1579** [comment]
hi @wytskshu ：

这个应该是 hamibot 本身的问题，估计是没有做适配。你可以通过下面的渠道向官方反映：

1. 在 [Hamibot 仓库](https://github.com/hamibot/hamibot) 提 issue
2. 在 [问大家社区](https://hamibot.com/questions) 当中创建新的问题
3. 给官方发邮件

如果目前使用的话，还是考虑更换更老的版本或者使用其它系统。

等你回复~
