### ISSUE TITLE
[Bug] 模板使用 ocr 代码参数类型不匹配

### ISSUE THREAD

**Issue by fangzongzhou** [batu1579/hamibot-starter#7]
`ocr.recognize(img);` 会提示以下内容

Argument of type 'CaptureImage' is not assignable to parameter of type 'Image'.
  Property 'recycle' is missing in type 'BaseImage' but required in type 'Image'.

**Comment by batu1579** [comment]
@fangzongzhou
我修改了一下，你在重新克隆下来试试。


抱歉耽搁这么久才回复你，最近在整 Hamibot 的 VSC 插件
